# Generated by Django 2.0.2 on 2018-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='Безымянный Гость', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(default='Малые #беня', max_length=50)),
                ('company', models.CharField(default='Частное лицо', max_length=50)),
                ('specialization', models.CharField(default='Ламер', max_length=100)),
                ('regdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_person', models.CharField(max_length=30)),
                ('regdate', models.DateField(auto_now_add=True)),
                ('tent_num', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
