# Generated by Django 2.0.3 on 2018-03-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0002_auto_20180325_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countdown.Member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countdown.Team')),
            ],
        ),
    ]
