# Generated by Django 2.0.3 on 2018-04-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0003_teamleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='team',
            name='regdate',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tent_num',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество мест'),
        ),
    ]
